# Generated by Django 4.2.6 on 2023-10-04 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CarModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model', models.CharField(max_length=50)),
                ('year', models.IntegerField()),
                ('countPlace', models.IntegerField()),
                ('typeCar', models.CharField(max_length=50)),
                ('capacityEngine', models.FloatField()),
            ],
            options={
                'db_table': 'car',
            },
        ),
    ]
